trigger:
  - none

pool:
  vmImage: "ubuntu-latest"

variables:
  - name: CCACHE_DIR
    value: /home/vsts/.ccache

steps:
  - script: |
      sudo apt update
      sudo apt install -y ccache
      export PATH="/usr/lib/ccache:$PATH"
      ccache -z # Reset ccache stats
    displayName: "Install and configure ccache"

  - task: Cache@2
    inputs:
      key: 'ccache | "$(Agent.OS)" | **/*.cpp, **/*.h'
      path: $(CCACHE_DIR)
      cacheHitVar: CACHE_RESTORED
    displayName: "Cache ccache directory"

  - script: |
      make
    workingDirectory: $(Build.SourcesDirectory)
    displayName: "Build with Makefile"

  - script: |
      ccache -s # Show ccache stats
    displayName: "Show ccache stats"
